---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  run_list:
  - recipe[apt]

- name: ubuntu-16.04
  run_list:
  - recipe[apt]

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[postgis::default]
  verifier:
    inspec_tests:
      - test/smoke/default
  attributes:
    postgresql:
      password:
        postgres: password
